name: Run backend tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Set env variable
        run: echo "BETTERSTACK_TOKEN_BACKEND_TESTS=${{ secrets.BETTERSTACK_TOKEN_BACKEND_TESTS }}" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
